SELECT
    P.IDPESSOA,
    TRIM(P.NOME) AS NOME,
    US.IDUSUARIO,
    TRIM(US.NOMEUSUARIO) AS USUARIOTS
FROM
    USUARIOSISTEMA US
        LEFT JOIN PESSOA P ON P.IDPESSOA = US.IDUSUARIO
WHERE QUERY_PARAM